name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        required: false
        default: 'false'
      custom_message:
        description: 'Enter a custom message'
        required: true

env:
  ACTIONS_STEP_DEBUG: true 

jobs:
  job2:
    if: ${{ github.event.inputs.run_job == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ github.event.inputs.custom_message }}"

      - name: Printing run-job boolean value
        if: ${{ github.event.inputs.run_job == 'true' }}
        run: |
          echo "run_job value is: ${{ github.event.inputs.run_job }}"
