name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        required: false
        default: false
        type: boolean
      custom_message:
        description: 'Enter a custom message'
        required: true
        type: string

jobs:
  job2:
    if: ${{ inputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ inputs.custom_message }}"
