name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        required: false
        default: false
        type: boolean
      custom_message:
        description: 'Enter a custom message'
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on: ubuntu-latest
    if: github.event.inputs.run_job == 'true'
    steps:
      - name: Printing Custom Message
        run: echo "${{ github.event.inputs.custom_message }}"
